language: java
jdk:
  - oraclejdk8

before_script:
  - mvn clean
  - mvn package
  - mvn deploy

deploy:
  provider: heroku
  api_key:
    {
      secure: $HEROKU_API_KEY
    }
  app: oauth-my-autorization-server